#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
cd "$repo_root"

items_dir="docs/kaizens/items"
mkdir -p "$items_dir"

extract_field() {
  local file="$1"
  local key="$2"
  local value
  value="$(rg --no-line-number --no-heading "^${key}:" "$file" | head -n1 | sed -E "s/^${key}:[[:space:]]*//")"
  printf "%s" "$value"
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

shopt -s nullglob
for f in "$items_dir"/KZN-*.md; do
  id="$(extract_field "$f" "ID")"
  title="$(extract_field "$f" "Title")"
  category="$(extract_field "$f" "Category")"
  status="$(extract_field "$f" "Status")"
  priority="$(extract_field "$f" "Priority")"
  impact="$(extract_field "$f" "Impact")"
  effort="$(extract_field "$f" "Effort")"
  updated="$(extract_field "$f" "Updated")"

  [[ -z "$id" ]] && continue
  printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
    "$id" "$category" "$title" "$status" "$priority" "$impact" "$effort" "$updated" "$f" >> "$tmp"
done

if [[ -s "$tmp" ]]; then
  sort -r -t $'\t' -k1,1 "$tmp" -o "$tmp"
fi

write_table() {
  local category_filter="$1"

  echo "| ID | Category | Title | Status | Priority | Impact | Effort | Updated | File |"
  echo "|---|---|---|---|---|---|---|---|---|"

  if [[ ! -s "$tmp" ]]; then
    return
  fi

  if [[ "$category_filter" == "all" ]]; then
    awk -F '\t' '{printf("| %s | %s | %s | %s | %s | %s | %s | %s | `%s` |\n", $1, $2, $3, $4, $5, $6, $7, $8, $9)}' "$tmp"
  else
    awk -F '\t' -v c="$category_filter" '$2==c {printf("| %s | %s | %s | %s | %s | %s | %s | %s | `%s` |\n", $1, $2, $3, $4, $5, $6, $7, $8, $9)}' "$tmp"
  fi
}

cat > docs/kaizens/_index.md <<EOF_INDEX
# Kaizen Index

This file is auto-generated by:

\`tools/codex-skills/org-clock-kaizen/scripts/update_index.sh\`

$(write_table all)
EOF_INDEX

write_category() {
  local file="$1"
  local key="$2"
  local title="$3"
  local scope="$4"

  cat > "$file" <<EOF_CAT
# $title

$scope

This file is auto-generated by:

\`tools/codex-skills/org-clock-kaizen/scripts/update_index.sh\`

$(write_table "$key")
EOF_CAT
}

write_category "docs/kaizens/ui.md" "ui" "UI Kaizens" "Scope: Compose UI, ViewModel-facing UX behavior, notification presentation and interaction."
write_category "docs/kaizens/domain.md" "domain" "Domain Kaizens" "Scope: application use-cases, service orchestration, time/clock business rules."
write_category "docs/kaizens/data.md" "data" "Data Kaizens" "Scope: repository, persistence, backup, SAF I/O, serialization boundaries."
write_category "docs/kaizens/infra-ci.md" "infra-ci" "Infra/CI Kaizens" "Scope: GitHub Actions, build/release automation, developer workflow tooling."
write_category "docs/kaizens/tests-quality.md" "tests-quality" "Tests/Quality Kaizens" "Scope: unit/UI/benchmark tests, observability of quality and regression risk controls."
write_category "docs/kaizens/security-privacy.md" "security-privacy" "Security/Privacy Kaizens" "Scope: permissions, secrets, data exposure, identity/auth and threat-reduction work."
write_category "docs/kaizens/docs-ops.md" "docs-ops" "Docs/Ops Kaizens" "Scope: operating guides, incident docs, runbooks, and maintenance practices."

echo "Updated docs/kaizens/_index.md and category dashboards"
